from django.shortcuts import render, redirect
from django.conf import settings
from .stripe import stripe

from item.models import Category, Item

from .forms import SignupForm

# Create your views here.
def index(request):
    items = Item.objects.filter(is_sold=False)[0:6]
    categories = Category.objects.all()
    return render(request, 'core/index.html', {
        'categories': categories,
        'items': items
    })

def contact(request):
    return render(request, 'core/contact.html')

def checkout(request):
    if request.method == 'POST':
        # Retrieve the token generated by Stripe.js
        token = request.POST.get('stripeToken')

        # Create a charge using the Stripe API
        try:
            charge = stripe.Charge.create(
                amount=1000,  # Amount in cents
                currency='usd',
                description='Example charge',
                source=token,
            )
            # Payment successful
            return render(request, 'core/stripe/success.html')
        except stripe.error.CardError as e:
            # Payment failed
            return render(request, 'core/stripe/error.html', {'error': e.error.message})

    return render(request, 'core/checkout.html', {'stripe_public_key': settings.STRIPE_PUBLIC_KEY})

def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/login/')
    else:
        form = SignupForm()
    return render(request, 'core/signup.html', {
        'form': form
    })